site_name: Sendos Docs
site_url: https://sendos.ai/
repo_name: "GitHub"
repo_url: https://github.com/sendos-ai/Docs-General
edit_uri: blob/main/docs

color_mode: auto

nav:
  - Home: index.md
  - About: about.md
