site_name: Sendos Docs
site_url: https://sendos.ai/
repo_name: "GitHub"
repo_url: https://github.com/sendos-ai/Docs-General
edit_uri: blob/main/docs

color_mode: auto
user_color_mode_toggle: True

theme:
  name: material

nav:
  - Inicio: index.md
  - Diseño UX/UI: design/index.md
  - BackEnd: backend/index.md
  - FrontEnd: frontend/index.md
  - Acerca de sendos: about.md
