site_name: Sendos Docs
site_url: https://sendos.ai/
repo_name: "GitHub"
repo_url: https://github.com/sendos-ai/Docs-General
edit_uri: blob/main/docs

copyright: "© 2024 Sendos AI"

extra_javascript:
  - js/extra.js

extra_css:
  - css/extra.css

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/sendos_iso.png

  font:
    text: Roboto
    code: Roboto Mono

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/sendos-ai/Docs-General
#   analytics:
#     provider: google
#     tracking_id: UA-XXXXXXXXX-X

nav:
  - Inicio: index.md
  - Release / Features: src/release.md
  - Diseño UX/UI: src/design.md
  - BackEnd: src/backend.md
  - FrontEnd: src/frontend.md
  - Acerca de sendos: about.md
  - Funcionalidades: src/functions.md
  - Requisitos: src/stack_requirements.md
  - Historia de usuario: src/user_history.md
